# Generated by Django 3.0.3 on 2020-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.IntegerField()),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-caseID'],
            },
        ),
    ]
